version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_APP_URL=http://t44oocgcg8cgs4k8k4gg80wo.104.37.187.180.sslip.io
    volumes:
      - ./data:/app/data
    restart: unless-stopped
