version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - BOLT_USERNAME=athompson
      - BOLT_PASSWORD=Beachzipper66
    restart: unless-stopped

networks:
  default:
    driver: bridge
