version: '3.8'

services:
  bolt:
    image: ghcr.io/thevahidal/bolt:latest
    container_name: bolt
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Database configuration
      - BOLT_DATABASE_URL=postgresql://bolt_user:${DB_PASSWORD}@db:5432/bolt_db
      # Security settings
      - BOLT_USERNAME=${ADMIN_USERNAME:-admin}
      - BOLT_PASSWORD=${ADMIN_PASSWORD}
      - BOLT_JWT_SECRET=${JWT_SECRET}
      # App configuration
      - NODE_ENV=production
      - TZ=UTC
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bolt_network
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: bolt-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bolt_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=bolt_db
    volumes:
      - bolt_db_data:/var/lib/postgresql/data
    networks:
      - bolt_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bolt_user -d bolt_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  bolt_network:
    driver: bridge

volumes:
  bolt_db_data:
    driver: local

# Environment variables needed:
# - DB_PASSWORD: PostgreSQL database password
# - ADMIN_USERNAME: Bolt admin username (defaults to 'admin')
# - ADMIN_PASSWORD: Bolt admin password
# - JWT_SECRET: Secret key for JWT token generation
