version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - BOLT_USERNAME=athompson
      - BOLT_PASSWORD=Beachzipper66
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
