version: '3.8'

services:
  app:
    image: bolt:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      - BOLT_DATABASE_URL=postgresql://postgres:Beachzipper66@db:5432/bolt
      - BOLT_USERNAME=athompson
      - BOLT_PASSWORD=Beachzipper66
      - BOLT_JWT_SECRET=eyJhbGciOiJIUzI1NiJ9X8B4z2pY9n3mK7vQ5tR8wL1xD0fG4jH6
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - bolt-network

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=Beachzipper66
      - POSTGRES_DB=bolt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bolt-network

networks:
  bolt-network:
    driver: bridge

volumes:
  postgres_data:
