version: '3.8'

services:
  bolt:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bolt-app
    ports:
      - "3000:3000"
    environment:
      - BOLT_DATABASE_URL=postgresql://postgres:Beachzipper66@bolt-db:5432/bolt
      - BOLT_USERNAME=athompson
      - BOLT_PASSWORD=Beachzipper66
      - BOLT_JWT_SECRET=eyJhbGciOiJIUzI1NiJ9X8B4z2pY9n3mK7vQ5tR8wL1xD0fG4jH6
      - NODE_ENV=production
    depends_on:
      - bolt-db
    networks:
      - bolt-network
    restart: unless-stopped

  bolt-db:
    image: postgres:14-alpine
    container_name: bolt-db
    environment:
      - POSTGRES_PASSWORD=Beachzipper66
      - POSTGRES_DB=bolt
    volumes:
      - bolt-data:/var/lib/postgresql/data
    networks:
      - bolt-network
    restart: unless-stopped

networks:
  bolt-network:
    name: bolt-network

volumes:
  bolt-data:
    name: bolt-data
