version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/bolt
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://posww0ccw0wws484wsccgwsk.104.37.187.180.sslip.io
      - NEXT_PUBLIC_APP_URL=http://posww0ccw0wws484wsccgwsk.104.37.187.180.sslip.io
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BOLT_USERNAME=${BOLT_USERNAME}
      - BOLT_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=bolt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
